fix: Change extra-files type from python to generic (task#269.3)
Release Please doesn't support 'python' as an extra file type.
Use 'generic' type which automatically handles Python version strings
like __version__ = "4.0.0b2".

Error: unsupported extraFile type: python
Ref: https://github.com/googleapis/release-please/issues